name: "godot-ci export"
on: 
  push: 
    branches: 
      - "*"

env:
  GODOT_VERSION: 4.1.1
  EXPORT_NAME: Flipbook
  # Set up these as Github Secrets:
  # ITCHIO_UPLOAD_KEY (the "butler" api key)
  # ITCHIO_USERNAME
  # ITCHIO_GAME

jobs:
  deploy-web:
    name: Web Export
    runs-on: ubuntu-latest
    container:
      image: docker://barichello/godot-ci:4.1.1
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Setup
        run: |
          mkdir -v -p build/web ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable

      - name: Web Build
        run: godot --headless -v --export-release "HTML5" ./build/web/index.html

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: web
          path: ./build/web/

      - name: Itch.io
        env: 
          BUTLER_API_KEY: ${{ secrets.ITCHIO_UPLOAD_KEY }}
        run: butler push ./build/web ${{ secrets.ITCHIO_USERNAME }}/${{ secrets.ITCHIO_GAME }}:web
